export const aboutContent = {
  en: {
    title: "Better care begins with listening.",
    lead: "We are a Melbourne-based allied health and support provider focused on practical care, clear communication and genuine respect.",
    enquiryCta: "Start an enquiry",
    servicesCta: "Explore our services",
    heroAlt: "A physiotherapist guiding a participant through resistance-band exercises at home",
    storyAlt: "A participant and family member planning support with a practitioner at home",
    standardsAlt: "A practitioner listening during a private consultation",
    storyTitle: "Care should make sense in daily life.",
    storyBody: [
      "Better Care Health Group works with participants, older people, families and referrers across Melbourne. Our mobile model helps us understand the real environments, routines and relationships around each person.",
      "We take time to understand what matters before recommending support. That means goals stay connected to everyday life, communication stays clear and the people you choose can remain part of the conversation.",
    ],
    principlesTitle: "What people can expect from us.",
    principlesIntro: "Our approach is straightforward: we listen, plan together and keep communication open as needs and priorities change.",
    principles: [
      { title: "Listen before planning", body: "We start by understanding what matters to you, your goals and what useful support looks like." },
      { title: "Practical in everyday life", body: "We focus on strategies and services that can work naturally within your routines and environment." },
      { title: "Clear communication", body: "We explain recommendations in plain language and make the next step easy to understand." },
      { title: "Review and adapt", body: "We check what is working and adjust goals or practical arrangements as circumstances change." },
    ],
    connectedTitle: "Support works better when it is connected.",
    connectedBody: "With your consent, we can collaborate with family, carers, support coordinators, care partners and treating professionals. This helps reduce repeated conversations and keeps the people involved working toward the same goals.",
    connectedStatement: "Your goals, choices and consent guide the work.",
    standardsTitle: "Professional care, backed by clear standards.",
    standardsBody: "Better Care Health Group is a Registered NDIS Provider. Practitioners hold the qualifications, registrations and checks required for their roles, including AHPRA registration where applicable.",
    standards: [
      "Qualified practitioners",
      "Safe and respectful practice",
      "Privacy and informed consent",
      "Ongoing review and communication",
    ],
    closingTitle: "Let’s talk about what would make support useful.",
    closingBody: "Share a few initial details and our team will contact you to discuss service fit, availability and the next step.",
    callCta: "Call 0452 638 779",
  },
  zh: {
    title: "更好的照护，从聆听开始。",
    lead: "我们是位于墨尔本的联合健康与支持服务机构，重视实用照护、清晰沟通和真诚尊重。",
    enquiryCta: "在线咨询",
    servicesCta: "浏览服务",
    heroAlt: "物理治疗师在客户家中指导弹力带训练",
    storyAlt: "参与者与家人在家中和专业人员一起规划支持",
    standardsAlt: "专业人员在私密咨询中认真聆听",
    storyTitle: "照护应当真正适合日常生活。",
    storyBody: [
      "Better Care Health Group 为墨尔本各地的参与者、长者、家庭及转介人员提供服务。上门服务让我们能够了解每个人真实的生活环境、日常习惯与支持关系。",
      "我们会先花时间了解什么对您最重要，再提出支持建议。这样，目标能与日常生活保持联系，沟通更清晰，您选择的人也可以继续参与讨论。",
    ],
    principlesTitle: "您可以期待我们的工作方式。",
    principlesIntro: "我们的方式很直接：先聆听、共同规划，并在需要和重点发生变化时保持开放沟通。",
    principles: [
      { title: "先聆听，再规划", body: "我们先了解对您重要的事情、您的目标，以及怎样的支持才真正有用。" },
      { title: "适合真实日常生活", body: "我们关注能够自然融入日常习惯与生活环境的策略和服务。" },
      { title: "清晰沟通", body: "我们用容易理解的语言说明建议，让下一步安排清楚明了。" },
      { title: "持续检视与调整", body: "我们会了解哪些安排有效，并随着情况变化调整目标或实际支持方式。" },
    ],
    connectedTitle: "彼此连接的支持，往往更有效。",
    connectedBody: "在获得您的同意后，我们可以与家人、照护者、支持协调员、照护伙伴及治疗专业人员合作，减少重复沟通，并让参与支持的人朝着共同目标前进。",
    connectedStatement: "您的目标、选择与同意，始终指导我们的工作。",
    standardsTitle: "专业照护，以清晰标准为基础。",
    standardsBody: "Better Care Health Group 是注册 NDIS 服务提供商。专业人员具备其岗位所需的资质、注册和审查要求，并在适用情况下持有 AHPRA 注册。",
    standards: [
      "具备资质的专业人员",
      "安全且尊重的服务实践",
      "隐私与知情同意",
      "持续检视与沟通",
    ],
    closingTitle: "让我们聊聊怎样的支持对您真正有用。",
    closingBody: "请提供一些基本信息，我们的团队会联系您，讨论服务是否合适、可用时间与下一步安排。",
    callCta: "致电 0452 638 779",
  },
} as const;
