import { PageHero } from "../_components/page-hero/PageHero";
import { company } from "../_content/site";
import type { Locale } from "../_i18n/locale";

const englishSections = [
  { title: "1. About this policy", paragraphs: [`This Privacy Policy explains how ${company.name} manages personal information collected through this website and in connection with enquiries about our services. ${company.legalName} is the legal entity responsible for this website.`, "We aim to manage personal information openly and in accordance with applicable Australian privacy requirements, including the Privacy Act 1988 (Cth) and the Australian Privacy Principles where they apply."] },
  { title: "2. Information we may collect", paragraphs: ["Depending on how you interact with us, we may collect your name, contact details, suburb, preferred communication method, relationship to the person seeking support, requested services and funding pathway.", "If an enquiry progresses, we may also collect information about goals, daily routines, disability, health, mobility, support needs, risks, service history, NDIS or aged care arrangements, authorised representatives and other people involved in care. Health and disability information is sensitive information and is handled with additional care.", "Our website may also receive limited technical information such as browser type, device information, pages visited and cookie data used for security, performance and basic website functionality."] },
  { title: "3. How we collect information", paragraphs: ["We generally collect information directly from you through the enquiry form, phone, email or later intake conversations.", "With appropriate consent or authority, information may also be provided by a family member, carer, nominee, support coordinator, health professional, aged care provider, plan manager or another referrer. We may confirm authority before discussing personal information."] },
  { title: "4. Why we collect and use information", paragraphs: ["We use personal information to respond to enquiries, assess service fit and availability, arrange appointments, plan and deliver services, communicate with authorised people, manage funding and administration, maintain service records, improve quality and safety, and meet legal or regulatory obligations.", "We do not sell personal information. We do not use detailed health or disability information for unrelated direct marketing."] },
  { title: "5. When information may be shared", paragraphs: ["Information may be shared with practitioners, support workers and authorised team members who need it to respond to an enquiry or deliver services. With consent or where otherwise permitted, we may also communicate with family members, nominees, referrers, treating professionals, NDIS or aged care organisations, plan managers and relevant funding bodies.", "We may use service providers for website hosting, email, secure record systems, technology support and professional advice. We may also disclose information where required or authorised by law, or where necessary to address a serious threat to health or safety."] },
  { title: "6. Website enquiries and cookies", paragraphs: ["Please keep the public enquiry form brief and do not include detailed medical histories, diagnostic reports or clinical documents. If further information is required, our team will explain a more appropriate way to provide it.", "Cookies and similar technologies may be used for essential website operation, security and performance. If analytics, Google Business or other optional services are introduced, this policy and any consent controls should be updated to reflect their use."] },
  { title: "7. Storage, security and overseas processing", paragraphs: ["We take reasonable steps to protect personal information from misuse, interference, loss and unauthorised access, modification or disclosure. Safeguards may include access controls, secure systems, staff procedures and careful selection of technology providers.", "Some website, email or technology providers may store or process information outside Australia. Provider locations can change, so you may contact us for current information about the systems relevant to your enquiry. We review provider arrangements and take reasonable steps appropriate to the information and service involved."] },
  { title: "8. Access and correction", paragraphs: ["You may ask to access personal information we hold about you or request that inaccurate, out-of-date, incomplete, irrelevant or misleading information be corrected. We may need to verify your identity or authority before responding. In some circumstances an exception may apply, and if we refuse a request we will explain the reason and available complaint options where required.", `Requests can be made by emailing ${company.email}, calling ${company.phone}, or writing to ${company.address}.`] },
  { title: "9. Privacy questions and complaints", paragraphs: [`If you have a privacy question or complaint, contact us at ${company.email}, ${company.phone}, or ${company.address}. Please describe your concern and how you would like us to respond. We will review it, may ask for further information, and aim to respond within a reasonable period, generally within 30 days.`, "If you are not satisfied after giving us an opportunity to respond, you may contact the Office of the Australian Information Commissioner at oaic.gov.au."] },
  { title: "10. Changes to this policy", paragraphs: ["We may update this policy when our services, systems, providers or legal obligations change. The current version will be published on this page with its last updated date."] },
];

const chineseSections = [
  { title: "1. 关于本政策", paragraphs: [`本隐私政策说明 ${company.name} 如何管理通过本网站及服务咨询收集的个人信息。${company.legalName} 是负责本网站的法律实体。`, "我们致力于公开管理个人信息，并在适用情况下遵守澳大利亚相关隐私要求，包括《1988 年隐私法》（联邦）及澳大利亚隐私原则。"] },
  { title: "2. 我们可能收集的信息", paragraphs: ["根据您与我们的互动方式，我们可能收集您的姓名、联系方式、所在城区、首选沟通方式、您与寻求支持人士的关系、所需服务及资金渠道。", "如果咨询继续进行，我们还可能收集有关目标、日常生活、残障、健康、行动能力、支持需要、风险、服务历史、NDIS 或老年照护安排、授权代表及其他参与照护人员的信息。健康与残障资料属于敏感信息，我们会给予额外保护。", "网站也可能接收有限的技术资料，例如浏览器类型、设备信息、访问页面及用于安全、性能和基本网站功能的 Cookie 数据。"] },
  { title: "3. 我们如何收集信息", paragraphs: ["我们通常通过咨询表格、电话、电子邮件或后续接收沟通直接向您收集信息。", "在获得适当同意或授权后，资料也可能由家人、照护者、受托人、支持协调员、医疗专业人员、老年照护机构、计划管理人或其他转介人员提供。讨论个人信息前，我们可能会确认相关权限。"] },
  { title: "4. 收集和使用信息的原因", paragraphs: ["我们使用个人信息回复咨询、评估服务适配和可用时间、安排预约、规划及提供服务、与获授权人员沟通、管理资金和行政事务、保存服务记录、改善质量与安全，以及履行法律或监管义务。", "我们不会出售个人信息，也不会将详细健康或残障资料用于无关的直接营销。"] },
  { title: "5. 何时可能共享信息", paragraphs: ["为回复咨询或提供服务，信息可能与需要使用资料的专业人员、支持工作者及获授权团队成员共享。在获得同意或法律允许的情况下，我们也可能与家人、受托人、转介人员、治疗专业人员、NDIS 或老年照护机构、计划管理人及相关资金机构沟通。", "我们可能使用网站托管、电子邮件、安全记录系统、技术支持及专业咨询服务商。法律要求或授权时，或为应对严重健康或安全威胁时，我们也可能披露相关信息。"] },
  { title: "6. 网站咨询与 Cookie", paragraphs: ["请保持公开咨询内容简洁，不要提供详细病史、诊断报告或临床文件。如需进一步资料，团队会说明更合适的安全提供方式。", "Cookie 和类似技术可能用于网站基本运行、安全及性能。如果未来加入分析工具、Google Business 或其他可选服务，我们会更新本政策及相关同意控制。"] },
  { title: "7. 储存、安全与海外处理", paragraphs: ["我们采取合理措施，保护个人信息免遭滥用、干扰、遗失、未经授权的访问、修改或披露。措施可能包括访问控制、安全系统、员工流程及谨慎选择技术服务商。", "部分网站、电子邮件或技术服务商可能在澳大利亚境外储存或处理信息。服务商地点可能发生变化，您可以联系我们了解与您咨询相关系统的最新情况。我们会审查服务商安排，并根据所涉及的信息和服务采取合理措施。"] },
  { title: "8. 查阅与更正", paragraphs: ["您可以申请查阅我们持有的个人信息，或要求更正不准确、过时、不完整、无关或具有误导性的资料。回复前我们可能需要确认您的身份或权限。某些情况下可能适用例外；如拒绝请求，我们会在需要时说明原因及可用投诉方式。", `您可以通过 ${company.email}、${company.phone} 或写信至 ${company.address} 提交申请。`] },
  { title: "9. 隐私问题与投诉", paragraphs: [`如有隐私问题或投诉，请通过 ${company.email}、${company.phone} 或 ${company.address} 联系我们。请说明您的疑虑及希望我们如何回复。我们会进行审查，可能要求进一步资料，并争取在合理时间内回复，通常不超过 30 天。`, "如果在给予我们回应机会后仍不满意，您可以联系澳大利亚信息专员办公室，网址为 oaic.gov.au。"] },
  { title: "10. 政策更新", paragraphs: ["当服务、系统、服务商或法律义务发生变化时，我们可能更新本政策。最新版本及更新日期会公布在本页面。"] },
];

export function PrivacyPageView({ locale }: { locale: Locale }) {
  const zh = locale === "zh";
  const sections = zh ? chineseSections : englishSections;
  return <main id="main-content">
    <PageHero title={zh ? "隐私政策" : "Privacy Policy"} locale={locale} showMedia={false}>{zh ? "Better Care Health Group 如何处理通过本网站、服务咨询及初步接收流程提供的个人信息。" : "How Better Care Health Group handles personal information provided through this website, service enquiries and early intake."}</PageHero>
    <section className="page-section"><div className="site-shell privacy-layout">
      <aside className="privacy-summary"><p className="eyebrow">{zh ? "最后更新" : "Last updated"}</p><p>{zh ? "2026 年 7 月 17 日" : "17 July 2026"}</p><p>{zh ? "本网站政策应与服务接收期间提供的服务专用隐私说明、同意书及记录处理程序一并阅读。" : "This website policy should be read alongside any service-specific privacy notices, consent forms and record-handling procedures provided during intake."}</p><a className="button button-white" href={`mailto:${company.email}`}>{zh ? "咨询隐私问题" : "Ask a privacy question"}</a></aside>
      <div className="privacy-sections">{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}</div>
    </div></section>
  </main>;
}
