import {
  Armchair,
  Baby,
  Broom,
  Bus,
  CookingPot,
  HandHeart,
  HouseLine,
  PersonSimpleWalk,
  Plant,
  Pulse,
  PuzzlePiece,
  Sparkle,
  UsersThree,
} from "@phosphor-icons/react/dist/ssr";

const clinicalServices = [
  {
    slug: "physiotherapy",
    title: "Physiotherapy",
    category: "Therapist-led care",
    summary: "Practical support for movement, mobility, strength and confidence at home and in the community.",
    intro: "Our physiotherapy service connects assessment and treatment with the places where movement matters most. We look at everyday routines, the home environment, personal goals and the wider care team before agreeing on a practical plan.",
    includes: ["Mobility, balance and falls risk assessment", "Strength, movement and functional exercise", "Pain and movement management strategies", "Home, equipment and carer recommendations"],
    helps: ["People whose mobility or confidence has changed", "NDIS participants working toward functional goals", "Older people who want to remain active at home"],
    approach: ["Assessment led by an AHPRA-registered physiotherapist", "Clear goals and recommendations in everyday language", "Review points that adapt to progress, feedback and changing needs"],
    imageKeywords: ["Australian home physiotherapy session natural daylight", "physiotherapist mobility assessment participant home Melbourne"],
    icon: PersonSimpleWalk,
  },
  {
    slug: "occupational-therapy",
    title: "Occupational Therapy",
    category: "Therapist-led care",
    summary: "Support with daily activities, home routines, independence and meaningful participation.",
    intro: "Occupational therapy looks at what a person wants and needs to do each day, then considers the skills, routines, environments and supports around those activities.",
    includes: ["Daily activity and functional assessment", "Home routines and environmental recommendations", "Equipment and assistive technology guidance", "Strategies for participation and independence"],
    helps: ["People finding everyday tasks harder", "Participants exploring equipment or environmental changes", "Families seeking practical strategies for daily life"],
    approach: ["Start with the activities that matter to the person", "Consider strengths, barriers and the real environment", "Coordinate recommendations with consent"],
    imageKeywords: ["occupational therapist home assessment Australia", "adaptive daily living activity therapist participant"],
    icon: PuzzlePiece,
  },
  {
    slug: "allied-health-assistance",
    title: "Allied Health Assistance",
    category: "Therapist-led care",
    summary: "Therapy support delivered under the delegation and guidance of a treating allied health professional.",
    intro: "Allied health assistants can help people practise agreed therapy activities between clinician reviews. Tasks remain within a documented program and the assistant's training, competence and delegated scope.",
    includes: ["Practice of delegated therapy activities", "Support with repetition and routine", "Progress observations for the treating clinician", "Home and community-based sessions"],
    helps: ["People with an established therapy program", "Participants who benefit from supported practice", "Families looking for continuity between reviews"],
    approach: ["Work from a current delegated therapy plan", "Stay within role, competence and supervision requirements", "Escalate changes or concerns to the treating clinician"],
    imageKeywords: ["allied health assistant exercise program home Australia", "therapy assistant supporting functional activity community"],
    icon: Pulse,
  },
  {
    slug: "myotherapy",
    title: "Myotherapy",
    category: "Therapist-led care",
    summary: "Individual care focused on muscle and soft tissue comfort, movement and function.",
    intro: "Myotherapy may support people experiencing muscle or soft tissue discomfort that affects movement and everyday activity. Service suitability is confirmed before appointments begin.",
    includes: ["Movement and soft tissue assessment", "Individual treatment planning", "Home movement and self-management guidance", "Review of response and next steps"],
    helps: ["People managing muscular discomfort", "People whose movement is limited by soft tissue symptoms", "Clients seeking practical self-management strategies"],
    approach: ["Clarify symptoms, goals and relevant health information", "Explain options, benefits and limits before treatment", "Refer on when needs sit outside service scope"],
    imageKeywords: ["professional myotherapy consultation Australia clinic", "therapist soft tissue movement assessment"],
    icon: HandHeart,
  },
];

const earlyChildhoodServices = [
  {
    slug: "early-childhood-supports",
    title: "Early Childhood Supports",
    code: "0118",
    category: "Early childhood",
    summary: "Family-centred early intervention for young children with developmental delay or disability in everyday settings.",
    intro: "Early childhood support works with the child and the people who know them best. The focus is on building skills, participation and family capability through daily routines at home, in the community and in early learning settings.",
    includes: ["Understanding the child's strengths, interests and support needs", "Family-centred goal setting and practical strategies", "Support within home, community and early learning routines", "Coordination across the child's team with family consent"],
    helps: ["Young children with developmental delay or disability", "Families wanting practical strategies for everyday routines", "Children building participation across home and community life"],
    approach: ["Include the child in age and developmentally appropriate ways", "Work collaboratively with families and chosen professionals", "Review goals as the child, family and circumstances change"],
    imageKeywords: ["Australian early childhood therapist family play home natural", "child developmental support everyday play family Australia"],
    icon: Baby,
  },
  {
    slug: "key-workers",
    title: "Key Worker Support",
    category: "Early childhood",
    summary: "One coordinated point of support for a child, family and the wider early childhood team.",
    intro: "A key worker helps bring goals, strategies and communication together so families are not left coordinating every professional conversation on their own.",
    includes: ["A consistent point of contact", "Family coaching within everyday routines", "Coordination with the wider team", "Progress review and shared planning"],
    helps: ["Families working with several professionals", "Children whose goals cross different daily settings", "Parents and carers seeking coordinated guidance"],
    approach: ["Agree who the family wants involved", "Keep information sharing consent-led", "Turn professional recommendations into practical routines"],
    imageKeywords: ["key worker family planning child development Australia", "early intervention team family home meeting"],
    icon: UsersThree,
  },
];

const dailyLivingServices = [
  {
    slug: "personal-care",
    title: "Personal Care",
    code: "0107",
    category: "Daily living",
    summary: "Respectful assistance with personal daily activities, routines, mobility and comfort at home.",
    intro: "Personal care is planned around privacy, dignity, communication, established routines and the person's preferred pace. We confirm the tasks, worker skills and safe support arrangements before service begins.",
    includes: ["Personal presentation and daily routines", "Meal and mobility assistance where agreed", "Prompts that support choice and independence", "Participant-specific safety and privacy arrangements"],
    helps: ["People who need reliable support with daily routines", "Participants building confidence at home", "Families seeking consistent, respectful assistance"],
    approach: ["Record preferences, consent and communication needs", "Match workers to the required skills and preferences", "Review routines when needs or circumstances change"],
    imageKeywords: ["respectful disability personal care home Australia", "support worker daily routine participant home natural"],
    icon: HandHeart,
  },
  {
    slug: "travel-transport",
    title: "Travel & Transport",
    code: "0108",
    category: "Daily living",
    summary: "Practical support to attend appointments, complete errands and access community activities.",
    intro: "Travel support is shaped around the destination, timing, access needs and the person's comfort. It may include planning and preparation as well as assistance during an agreed journey.",
    includes: ["Travel to appointments and activities", "Shopping and community errands", "Journey planning and preparation", "Building confidence with familiar travel routines"],
    helps: ["Participants who need reliable travel assistance", "People attending regular appointments", "People building confidence with community access"],
    approach: ["Confirm the purpose, route and support needs", "Plan for mobility, timing and access requirements", "Review what makes each journey work well"],
    imageKeywords: ["disability transport support Melbourne appointment", "support worker community travel participant Australia"],
    icon: Bus,
  },
  {
    slug: "daily-tasks-shared-living",
    title: "Daily Tasks & Shared Living",
    code: "0115",
    category: "Daily living",
    summary: "Support with daily responsibilities, shared routines and practical home-based tasks.",
    intro: "Shared living support works best when expectations, preferences and responsibilities are clear. We help establish routines that respect each participant's choices and the needs of the household.",
    includes: ["Daily routine and household planning", "Meal and shared task support", "Prompts for everyday responsibilities", "Communication around shared living routines"],
    helps: ["Participants in shared living arrangements", "People seeking clearer home routines", "Households coordinating regular daily support"],
    approach: ["Understand the household rhythm and each person's role", "Document agreed routines and boundaries", "Review arrangements when the household changes"],
    imageKeywords: ["supported shared living daily routine Australia", "disability support shared kitchen planning home"],
    icon: HouseLine,
  },
  {
    slug: "supported-independent-living",
    title: "Supported Independent Living",
    code: "0138",
    category: "Daily living",
    summary: "Regular assistance with daily life for participants living in a shared or individual home setting.",
    intro: "Supported Independent Living is planned around the participant's approved supports, daily needs, preferences and home goals. Clear interfaces, worker competence and continuity are central to safe delivery.",
    includes: ["Regular daily living assistance", "Home-based skill development", "Shared household responsibilities", "Continuity and contingency planning"],
    helps: ["Participants who require regular support at home", "People building independent living skills", "Families planning stable home-based supports"],
    approach: ["Separate housing arrangements from support choices", "Co-design routines, responsibilities and safeguards", "Plan for worker changes and service continuity"],
    imageKeywords: ["supported independent living home Australia participant", "SIL shared home routine disability support"],
    icon: Armchair,
  },
  {
    slug: "development-life-skills",
    title: "Development of Daily Living & Life Skills",
    code: "0117",
    category: "Daily living",
    summary: "Practical skill-building for routines, planning, cooking, communication and everyday decision-making.",
    intro: "Life skills support breaks goals into practical steps that can be practised in real settings. The focus is on building capability and choice, not taking tasks over.",
    includes: ["Cooking and household routines", "Planning, budgeting and decision-making", "Communication and community confidence", "Repeatable steps toward greater independence"],
    helps: ["Participants working toward independence goals", "People who want to build daily living confidence", "Families seeking practical skill development"],
    approach: ["Choose a meaningful, observable goal", "Practise in the setting where the skill is used", "Adjust the pace based on feedback and progress"],
    imageKeywords: ["NDIS life skills cooking support Australia", "participant budgeting planning daily living support"],
    icon: CookingPot,
  },
  {
    slug: "household-tasks",
    title: "Household Tasks",
    code: "0120",
    category: "Daily living",
    summary: "Practical help with household routines that support a safer, more comfortable home.",
    intro: "Household task support respects how the participant wants their home to feel and function. Tasks and boundaries are agreed before delivery begins.",
    includes: ["Light cleaning and home routines", "Laundry and linen support", "Kitchen organisation", "Practical prompts to maintain the home"],
    helps: ["Participants who need support maintaining their home", "People seeking consistent household routines", "Families coordinating practical daily assistance"],
    approach: ["Agree on tasks, priorities and preferred routines", "Support safe participation where appropriate", "Review the arrangement as needs change"],
    imageKeywords: ["NDIS household tasks support Australia home", "support worker laundry routine participant natural"],
    icon: Broom,
  },
];

const communityServices = [
  {
    slug: "innovative-community-participation",
    title: "Innovative Community Participation",
    code: "0116",
    category: "Community participation",
    summary: "Goal-based support to build confidence, capacity and meaningful local connection.",
    intro: "Innovative community participation can help a person explore new interests and opportunities in a way that connects with their individual goals, comfort and strengths.",
    includes: ["Exploring interests and local opportunities", "Confidence in unfamiliar settings", "Practical social and community skills", "Goal-based participation planning"],
    helps: ["People wanting to try new community experiences", "Participants building confidence outside home", "People seeking purposeful local connection"],
    approach: ["Start with the participant's own idea of connection", "Build from familiar to new experiences", "Review whether activities remain meaningful"],
    imageKeywords: ["innovative community participation disability Australia", "participant creative community activity support"],
    icon: Sparkle,
  },
  {
    slug: "community-participation",
    title: "Community Participation",
    code: "0125",
    category: "Community participation",
    summary: "Support to attend activities, pursue interests and stay connected with the local community.",
    intro: "Community participation is personal. It can involve familiar places, new interests, social connection or practical help to make regular activities more achievable.",
    includes: ["Attending activities and appointments", "Support with hobbies and interests", "Social confidence and participation", "Planning safe community access"],
    helps: ["Participants wanting stronger community connection", "People building independence outside the home", "People who want support to pursue an interest"],
    approach: ["Choose activities that genuinely matter", "Plan access, communication and support needs", "Keep the participant in control of pace and choice"],
    imageKeywords: ["NDIS community participation Melbourne market", "disability support community activity Australia"],
    icon: Plant,
  },
  {
    slug: "group-centre-activities",
    title: "Group & Centre Activities",
    code: "0136",
    category: "Community participation",
    summary: "Structured group or centre-based activities supporting participation, confidence and social connection.",
    intro: "Group activities should be purposeful, inclusive and suited to the people attending. We discuss goals, accessibility and support needs before recommending a program.",
    includes: ["Inclusive group activities", "Creative, social or practical programs", "Confidence in shared settings", "Support to participate at an individual pace"],
    helps: ["People seeking structured social connection", "Participants exploring shared interests", "People who benefit from supported group participation"],
    approach: ["Match the activity to interests and goals", "Plan communication and access requirements", "Invite feedback about comfort and participation"],
    imageKeywords: ["inclusive disability group activity centre Australia", "NDIS creative group program natural photography"],
    icon: UsersThree,
  },
  {
    slug: "support-workers",
    title: "Support Workers",
    category: "Community participation",
    summary: "Reliable assistance with daily living, community access and the routines that matter to each person.",
    intro: "Support workers deliver agreed supports in line with the participant's service agreement and support plan. Matching, competence, communication and continuity all shape a good working relationship.",
    includes: ["Daily living and community assistance", "Support with agreed routines and goals", "Clear progress notes and escalation", "Worker matching and continuity where possible"],
    helps: ["Participants seeking regular practical assistance", "People who value consistent workers", "Families coordinating home and community support"],
    approach: ["Record worker preferences and required competencies", "Introduce roles and boundaries clearly", "Respond promptly to feedback or changing needs"],
    imageKeywords: ["NDIS support worker participant Melbourne community", "disability support everyday routine Australia"],
    icon: HouseLine,
  },
];

export const serviceGroups = {
  clinical: clinicalServices,
  earlyChildhood: earlyChildhoodServices,
  dailyLiving: dailyLivingServices,
  community: communityServices,
};

export const services = [
  ...clinicalServices,
  ...earlyChildhoodServices,
  ...dailyLivingServices,
  ...communityServices,
];

export type Service = (typeof services)[number];
